### ISSUE TITLE
Support for angular

### ISSUE THREAD

**Issue by dvalley56** [trycourier/courier-react#467]
Hii courier team,

I am using an angular application, I am already using courier email and it works flawlessly.
I wanted to integrate the courier inbox, but I am not able to. I went to the [documentation](https://www.courier.com/docs/inbox/web/javascript-sdk/) but it didn't work, it throwed an error.

```
v3.9.1.js:2  Uncaught (in promise) TypeError: Cannot read properties of null (reading 'appendChild')
    at v3.9.1.js:2:261530
    at f (v3.9.1.js:2:6744)
    at Generator.<anonymous> (v3.9.1.js:2:8062)
    at Generator.next (v3.9.1.js:2:7154)
    at e (v3.9.1.js:2:249976)
    at u (v3.9.1.js:2:261900)
    at v3.9.1.js:2:261959
    at new Promise (<anonymous>)
    at v3.9.1.js:2:261840
    at v3.9.1.js:2:262002
```

where `at v3.9.1.js:2:261530` pointed to the line

![image](https://github.com/trycourier/courier-react/assets/67868355/79cbfd0a-6b01-462b-b94f-a2664af8c303)

I would love to see an example or a guide I can follow. 
Thank you.

**Comment by madelacerda** [comment]
Hey! im having the same issue, did you find a way around it?

**Comment by dvalley56** [comment]
> Hey! im having the same issue, did you find a way around it? 

Yeah, I had something I don't remember if I had manages to get it co.pletely working. It way long back, I will share it with you later today.
